### ISSUE TITLE
之前IDE旧版本也不行..现在更新了还是不行呜呜

### ISSUE THREAD

**Issue by zsqw123** [flyAkari/ESP8266_Network_Clock#1]
Arduino:1.8.10 (Windows 10), 开发板："NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new can abort), All SSL ciphers (most compatible), 4MB (FS:1MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\DateStrings.cpp.o: in function `monthStr(unsigned char)':

C:\Users\damyj\Documents\Arduino\libraries\Time/DateStrings.cpp:71: multiple definition of `monthStr(unsigned char)'; sketch\DateStrings.cpp.o:sketch/DateStrings.cpp:71: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\DateStrings.cpp.o: in function `monthShortStr(unsigned char)':

C:\Users\damyj\Documents\Arduino\libraries\Time/DateStrings.cpp:77: multiple definition of `monthShortStr(unsigned char)'; sketch\DateStrings.cpp.o:sketch/DateStrings.cpp:77: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\DateStrings.cpp.o: in function `dayStr(unsigned char)':

C:\Users\damyj\Documents\Arduino\libraries\Time/DateStrings.cpp:85: multiple definition of `dayStr(unsigned char)'; sketch\DateStrings.cpp.o:sketch/DateStrings.cpp:85: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\DateStrings.cpp.o: in function `dayShortStr(unsigned char)':

C:\Users\damyj\Documents\Arduino\libraries\Time/DateStrings.cpp:91: multiple definition of `dayShortStr(unsigned char)'; sketch\DateStrings.cpp.o:sketch/DateStrings.cpp:91: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `breakTime(long, tmElements_t&)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:151: multiple definition of `breakTime(long, tmElements_t&)'; sketch\Time.cpp.o:sketch/Time.cpp:151: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `refreshCache(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:42: multiple definition of `refreshCache(long)'; sketch\Time.cpp.o:sketch/Time.cpp:42: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `hour(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:53: multiple definition of `hour(long)'; sketch\Time.cpp.o:sketch/Time.cpp:53: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `isPM(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:84: multiple definition of `isPM(long)'; sketch\Time.cpp.o:sketch/Time.cpp:84: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `isAM(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:76: multiple definition of `isAM(long)'; sketch\Time.cpp.o:sketch/Time.cpp:76: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `hourFormat12(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:62: multiple definition of `hourFormat12(long)'; sketch\Time.cpp.o:sketch/Time.cpp:62: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `minute(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:92: multiple definition of `minute(long)'; sketch\Time.cpp.o:sketch/Time.cpp:92: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `second(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:101: multiple definition of `second(long)'; sketch\Time.cpp.o:sketch/Time.cpp:101: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `day(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:110: multiple definition of `day(long)'; sketch\Time.cpp.o:sketch/Time.cpp:110: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `weekday(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:119: multiple definition of `weekday(long)'; sketch\Time.cpp.o:sketch/Time.cpp:119: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `month(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:128: multiple definition of `month(long)'; sketch\Time.cpp.o:sketch/Time.cpp:128: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `year(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:137: multiple definition of `year(long)'; sketch\Time.cpp.o:sketch/Time.cpp:137: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `makeTime(tmElements_t const&)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:204: multiple definition of `makeTime(tmElements_t const&)'; sketch\Time.cpp.o:sketch/Time.cpp:204: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `setTime(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:274: multiple definition of `setTime(long)'; sketch\Time.cpp.o:sketch/Time.cpp:274: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o:C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:242: multiple definition of `getTimePtr'; sketch\Time.cpp.o:sketch/Time.cpp:242: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `now()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:250: multiple definition of `now()'; sketch\Time.cpp.o:sketch/Time.cpp:250: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `hour()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:49: multiple definition of `hour()'; sketch\Time.cpp.o:sketch/Time.cpp:49: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `hourFormat12()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:58: multiple definition of `hourFormat12()'; sketch\Time.cpp.o:sketch/Time.cpp:58: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `isAM()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:72: multiple definition of `isAM()'; sketch\Time.cpp.o:sketch/Time.cpp:72: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `isPM()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:80: multiple definition of `isPM()'; sketch\Time.cpp.o:sketch/Time.cpp:80: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `minute()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:88: multiple definition of `minute()'; sketch\Time.cpp.o:sketch/Time.cpp:88: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `second()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:97: multiple definition of `second()'; sketch\Time.cpp.o:sketch/Time.cpp:97: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `day()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:106: multiple definition of `day()'; sketch\Time.cpp.o:sketch/Time.cpp:106: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `weekday()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:115: multiple definition of `weekday()'; sketch\Time.cpp.o:sketch/Time.cpp:115: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `month()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:124: multiple definition of `month()'; sketch\Time.cpp.o:sketch/Time.cpp:124: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `year()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:133: multiple definition of `year()'; sketch\Time.cpp.o:sketch/Time.cpp:133: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `setTime(int, int, int, int, int, int)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:286: multiple definition of `setTime(int, int, int, int, int, int)'; sketch\Time.cpp.o:sketch/Time.cpp:286: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `adjustTime(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:303: multiple definition of `adjustTime(long)'; sketch\Time.cpp.o:sketch/Time.cpp:303: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `timeStatus()':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:307: multiple definition of `timeStatus()'; sketch\Time.cpp.o:sketch/Time.cpp:307: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `setSyncProvider(long (*)())':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:312: multiple definition of `setSyncProvider(long (*)())'; sketch\Time.cpp.o:sketch/Time.cpp:312: first defined here

c:/users/damyj/appdata/local/arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/2.5.0-4-b40a506/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: libraries\Time\Time.cpp.o: in function `setSyncInterval(long)':

C:\Users\damyj\Documents\Arduino\libraries\Time/Time.cpp:319: multiple definition of `setSyncInterval(long)'; sketch\Time.cpp.o:sketch/Time.cpp:319: first defined here

collect2.exe: error: ld returned 1 exit status

"TimeLib.h" 对应多个库
 已使用： C:\Users\damyj\Documents\Arduino\libraries\Time
"ESP8266WiFi.h" 对应多个库
 已使用： C:\Users\damyj\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\ESP8266WiFi
"SPI.h" 对应多个库
 已使用： C:\Users\damyj\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.1\libraries\SPI
exit status 1
为开发板 NodeMCU 1.0 (ESP-12E Module) 编译时出错。

在文件 -> 首选项开启
“编译过程中显示详细输出”选项
这份报告会包含更多信息。

**Comment by flyAkari** [comment]
开发环境没配好，代码没问题
