### ISSUE TITLE
ssid和密码没有起作用

### ISSUE THREAD

**Issue by peking2008** [flyAkari/ESP8266_Network_Clock#3]
手机列表里显示的wifi名称为：flayAkri而且没有密码，并不是程序里设置的:
#define DEF_WIFI_SSID     "D1"
#define DEF_WIWI_PASSWORD "01234567890"

**Comment by flyAkari** [comment]
这个DEF可以改成你家里WiFi的名和密码，不是热点的名和密码，热点没设密码。

**Comment by peking2008** [comment]
好的，明白了，谢谢。此热点如果也能加上默认密码，这样就更安全了。
